ignore package-lock.json in scheduler
probot/scheduler pull request #14
Opened 2017-10-14 18:12 UTC by nileshgulia1

2017-10-14 18:18 UTC, nileshgulia1 commented
# probot/probot#291

2017-10-14 18:31 UTC, bkeepers requested changes

2017-10-14 18:31 UTC, bkeepers commented on .gitignore
> +node_modules/package-lock.json
It looks like this file didn't have a trailing newline, so the command to append to this file didn't work right. Can you add a newline between `node_modules/` and `package-lock.json`?

2017-10-15 09:14 UTC, nileshgulia1 commented
@bkeepers  please review the change

2017-10-15 11:39 UTC, merged